### ISSUE TITLE
11.3

### ISSUE THREAD

**Issue by chaoskagami** [chaoskagami/corbenik#58]
10.3 fixed a number of vulnerabilities (notably the ones used on 10.2 to get a9lh), and unfortunately, also bumped minver. There's no reason, ABI/API wise that should be needed, but it was probably done to prevent FIRM downgrade. NS now panics if the kernel is not the version intended for 10.3.

As of now, one needs 10.3 FIRM to boot 10.3 NAND.

I strongly recommend people hold back for now; it doesn't work without 10.3 FIRM, and quite a few things are now broken and in need of fixing.

**Comment by chaoskagami** [comment]
https://www.3dbrew.org/wiki/11.3.0-36

So, the TODO list:

- [x] Update fpdver
- [x] Check DG listing and update accordingly if needed (not needed)
- [ ] Possibly write a patch to disable the safefirmhax fix (need to analyze the code for this, but 3dbrew has a good description; either I nop the check, nop the set, or change the set to 0)
- [x] Firmlaunch hook broke. Probably because it's a crappy hybrid of cakes and Luma. Now would be a good opportunity to rewrite it into something more sane. (Fixed; cleaning up before merge to master)

It's unfortunate that every firmware version just gets slower and less optimal. Oh well.

**Comment by NinjaBoyLao** [comment]
i think you may have meant 11.3

**Comment by chaoskagami** [comment]
I did. Even more embarassing is that I screwed that up approximately five times on #cakey too. T_T

**Comment by chaoskagami** [comment]
I'm closing this. All main functionality has been fixed for 11.3.

Some misc stuff needs cleanup, and it's possible I may want additional changes (read: disabling "svcFixGspwn") but otherwise support for 11.3 is there now, so this is no longer an "issue."

**Comment by NinjaBoyLao** [comment]
How do I make sure the corbenik I have is the working one? I can compile it myself i think, but i'm not trusting my own builds right now since the hashes don't match the ones on ~~jeeves~~ jenkins (everything seemingly works as it should regardless)

**Comment by chaoskagami** [comment]
The hashes not matching is probably normal; I haven't gone through any specific steps to ensure reproducible builds, so depending on your toolchain, it's entirely possible to get different (but correct) output. There's nothing I can do about this; but if you clone it off github and build it with r46, you have roughly the same thing as jenkins (and unless your toolchain isn't sane, should work identically even if the hash is different)

If it's built from any commit after https://github.com/chaoskagami/corbenik/commit/e1cadf4d72c2c98150e153fadae145c1fc022eae then the main incompatibility (firmlaunch) has been refactored.
