### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by chaoskagami** [chaoskagami/corbenik#8]
This is to keep track of build failures on windows. Currently known, actual issues:
- [x] Mingw is unusable.
- [x] bdfe misgenerates font.h on Cygwin for one specific character. I'm unsure why.
- [ ] Python shebang causes issues on Windows. Find some way to get the correct python in the Makefile on windows targets.

This is only for keeping track of them. Note that I don't actually care if it's buildable on Windows.

**Comment by chaoskagami** [comment]
Windows builds are too much damned effort for little to no gain. Use a VM.

**Comment by fox8091** [comment]
If it means anything, I managed to get it working with some minor tweaks. :) Using MinGW btw.

**Comment by chaoskagami** [comment]
Getting it to work is nice and all, but it's too much effort for me to support especially when things change all the time. I'm glad it works for you. 

I just don't have the time nor patience to officially support it.

The only reason Windows works at the moment is because when I forked and cut down bdfe, I also apparently made it mingw compatible.

**Comment by fox8091** [comment]
Anyway, as far as Python, it requires changing it to python instead of python2.

**Comment by chaoskagami** [comment]
I've already explained the reasons I won't be doing that. python should not be assumed to be python2 on Linux systems, and on Windows there's all the %PATH% crap to deal with.
